# Generated by Django 3.2.12 on 2022-03-04 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWorkSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=200, null=True)),
                ('client_org', models.CharField(max_length=200, null=True)),
                ('engineer', models.CharField(max_length=200, null=True)),
                ('manager', models.CharField(max_length=200, null=True)),
                ('report', models.TextField()),
                ('recommendation', models.TextField()),
                ('action_work_required', models.TextField()),
                ('arrival_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('departure_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('vehicle_reg', models.CharField(max_length=10)),
                ('start_mileage', models.IntegerField()),
                ('end_mileage', models.IntegerField()),
                ('location', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('department', models.CharField(max_length=300)),
                ('job_number', models.CharField(max_length=100, null=True)),
                ('time_spent', models.CharField(max_length=30, null=True)),
                ('distance_covered', models.IntegerField(null=True)),
                ('client_signature', models.TextField()),
                ('engineer_signature', models.TextField()),
                ('client_sig_pic', models.FileField(upload_to='work_sheet/')),
                ('engineer_sig_pic', models.FileField(upload_to='work_sheet/')),
                ('work_sheet_images', models.FileField(blank=True, null=True, upload_to='work_sheet/')),
            ],
            options={
                'verbose_name': 'Daily Work Sheet',
                'verbose_name_plural': 'Daily Work Sheets',
            },
        ),
    ]
