# Generated by Django 3.2.12 on 2022-03-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyworksheet',
            name='client_sig_pic',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='dailyworksheet',
            name='engineer_sig_pic',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='dailyworksheet',
            name='work_sheet_images',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
