# Generated by Django 3.2.12 on 2022-03-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220305_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyworksheet',
            name='work_sheet_images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
